baseURL = "https://vangiangtrithuc-code.github.io/"
languageCode = "vi-vn"
title = "Blog của Giang"
theme = "PaperMod"

[pagination]
pagerSize = 10

[params]
ShowReadingTime = true
ShowShareButtons = true
ShowCodeCopyButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true