baseURL = "https://vangiangtrithuc-code.github.io/"
defaultContentLanguage = "vi"

[languages]
  [languages.vi]
    languageName = "Tiếng Việt"
    weight = 1
title = "Giang Blog"
theme = "PaperMod"

enableRobotsTXT = true
enableEmoji = true

[pagination]
pagerSize = 10

[taxonomies]
tag = "tags"
category = "categories"

[params]
author = "Ngô Văn Giang"
defaultTheme = "auto"
ShowReadingTime = true
ShowShareButtons = true
ShowCodeCopyButtons = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowToc = true
TocOpen = false
description = "Chia sẻ kiến thức ASP.NET Core, React, Electron, SQL Server, Windows."

[params.homeInfoParams]
Title = "👋 Xin chào, mình là Ngô Văn Giang"
Content = """
Backend Developer.

🚀 ASP.NET Core  
⚛️ React  
🖥 Electron  
🗄 SQL Server  

Chia sẻ kiến thức lập trình, kinh nghiệm thực tế và các dự án mình thực hiện.
"""

[params.label]
text = "Giang Blog"
icon = "/images/logo.png"
iconHeight = 28

[[params.socialIcons]]
name = "github"
url = "https://github.com/vangiangtrithuc-code"

[[params.socialIcons]]
name = "email"
url = "mailto:dkgiang.a2@gmail.com"

[[menu.main]]
identifier = "posts"
name = "Bài viết"
url = "/posts/"
weight = 1

[[menu.main]]
identifier = "about"
name = "Giới thiệu"
url = "/about/"
weight = 2

[[menu.main]]
identifier = "categories"
name = "Chuyên mục"
url = "/categories/"
weight = 3

[[menu.main]]
identifier = "projects"
name = "Dự án"
url = "/projects/"
weight = 4

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 5